Code Simplification & working film description
Sylicium/zone-telechargement-api pull request #4
Opened 2023-08-10 18:15 UTC by matthieuEv

J'ai retravaillé tout le système pour récupérer les données de la page web avec `cheerio`
```shell
npm install cheerio
```

la fonction `getMovieDetails` fonctionne grace à TheMovieDb. Il faut donc un fichier .env avec:

```txt
MOVIESDB_API_KEY=<your api key>
```
```shell
npm install dotenv
```

[TheMovieDb api key](https://developer.themoviedb.org/docs/getting-started)

2023-08-11 01:38 UTC, Sylicium commented on localModules/ztParser.js
> +    constructor(devMode=false,timeStamp=false, axiosRequestTimeInBetween=300) {
Je vois pas à quoi sert cette variable timeStamp. On dirais qu'elle fait l'effet de devMode, tu t'es trompé ?

2023-08-11 13:58 UTC, Sylicium requested changes
Approved for branche cheerio.
However i prefer to keep the old getMovieDetails() function for technical reasons (we are fetching zt, so we need to send zt datas). So i prefer you to re put that function and rename it getPageDatas()

2023-08-11 14:04 UTC, matthieuEv commented
Pour `this._timeStamp`, c'est parce que tu avais ça en commentaire:

```js
        // console.log("========================================================")
        // console.log("A:",Date.now()-this._lastAxiosRequestTimestamp)
        // console.log("B:",this._axiosRequestTimeInBetween)
        // console.log("C:",this._axiosRequestTimeInBetween - (Date.now()-this._lastAxiosRequestTimestamp))
        // console.log("--------------------------------------------------------")
```

 et je me suis dit qu'il faudrai une manière de l'afficher si t'en a vraiment besoin. 
Ok pour getPageDatas().

2023-08-11 14:07 UTC, Sylicium commented
C'est bien ce que je me disais alors, tu peux le retirer c'est des lignes de débug que j'ai oublié d'enlever x)
D'ailleurs je sais plu si le système de cooldown marche vraiment donc jpense que je le remodifierais plus tard

2023-08-11 14:07 UTC, matthieuEv commented
par contre je me demande du coup, vu que ZtParser c'est un module nodeJs, je pense que toute la partie Bot Discord devrait être un autre repo à part entière, peut être un fork de ce repo, pour que le code soit plus clair. Aussi du coup enlever pour l'instant la partie api

2023-08-11 14:13 UTC, Sylicium commented
> par contre je me demande du coup, vu que ZtParser c'est un module nodeJs, je pense que toute la partie Bot Discord devrait être un autre repo à part entière, peut être un fork de ce repo, pour que le code soit plus clair. Aussi du coup enlever pour l'instant la partie api

Yup, à vrai dire ça serais bien d'en faire directement un module NPM mais faut que je voie si c'est légal (et légal d'avoir ce repo d'ouvert d'ailleurs aussi ^^')

Et aussi je sais pas trop comment tu t'es débrouillé pour compacter tout avec cheerio, mais sache qu'une TRES grande partie du code servais pour détecter tous les cas possibles, car (cf. l'image ci dessous) dans ces menus là des fois y'a pas certaines infos, ce qui fait que si on récupère juste les <span> et qu'on prend le 1er, 2eme, 3eme, etc.. pour le mettre dans les variables qu'on pense être "Origine", "Durée", "Réalisation", etc.. bah en fait ça peut parfois être décalé. Donc j'avais fait un système qui checkais d'abord le titre de la ligne pour attribuer sa valeur au bon endroit. Comme ça meme si y'a que "Critiques des spectateurs" bah ça le mettre bien.
Ducoup voilà je sais pas si t'as fait un truc pour ça dans cheerio. Je voulais ajouter des checks pour vérifier ça en unit test mais j'avais la flemme x) mais faudras les rajouter
![image](https://github.com/Sylicium/zone-telechargement-api/assets/96630108/9a436a45-d7dd-497a-8a5e-3a8051743c21)

2023-08-11 14:19 UTC, matthieuEv commented
> Yup, à vrai dire ça serais bien d'en faire directement un module NPM mais faut que je voie si c'est légal (et légal d'avoir ce repo d'ouvert d'ailleurs aussi ^^')

Ouai pour le module NPM, mais t'as raison sur la légalité. Mais techniquement je pense que c'est bon vu qu'on fait juste du scrapping de site web...

> Et aussi je sais pas trop comment tu t'es débrouillé pour compacter tout avec cheerio, mais sache qu'une TRES grande partie du code servais pour détecter tous les cas possibles, car (cf. l'image ci dessous) dans ces menus là des fois y'a pas certaines infos, ce qui fait que si on récupère juste les et qu'on prend le 1er, 2eme, 3eme, etc.. pour le mettre dans les variables qu'on pense être "Origine", "Durée", "Réalisation", etc.. bah en fait ça peut parfois être décalé. Donc j'avais fait un système qui checkais d'abord le titre de la ligne pour attribuer sa valeur au bon endroit. Comme ça meme si y'a que "Critiques des spectateurs" bah ça le mettre bien.

En fait je fais pas élément par élément, 
je lis le html qui est dans la balise `center`, et je récupère la `strong` qui contient la balise `u` avec par exemple `Durée`, et je lis l'élément suivant. Donc normalement ça devrait pas trop poser de soucis
![image](https://github.com/Sylicium/zone-telechargement-api/assets/95125079/aa553076-7f61-4b57-b61b-bace4a0d3127)

2023-08-11 14:26 UTC, Sylicium commented
Dac pour cheerio, dans tous les cas un jour j'écrirais des unit tests pour passer mon code, et si ça passe pas avec cheerio c'est que ça sera pas bon x)

Et pour la légalité oui techniquement le site est public, et j'ai pensé même rendre neutre le module, c'est à dire que l'url n'est aps déjà dedans et donc _techniquement_ ça peut servir pour n'importe quel site web et on a juste a spécifier l'url du site à utiliser.
Sauf que le scrapping est déjà illégal si le site l'autorise pas, or là le site est déjà borderline donc il a pas de mention légales à proprement parler décrivant comment utiliser les API et si on peut scrapper ou pas xD
Du coup je sais pas si par défaut si pas spécifié c'est interdit ou pas, mais dans tous les cas ça reste de l'automatisation et de la récupération d'informations donc c'est aussi borderline..
J'avais déjà fermé l'API parce qu'un pote m'avais prévenu que du jour au lendemain je pouvais recevoir une amende sans préavis, donc j'ai préféré la couper avant que ça arrive x)

2023-08-11 14:32 UTC, matthieuEv commented
Dans ce cas la il suffit juste de mettre un avertissement au tout début du readme pour dire que ce repo est fait à des fin d'apprentissage et qu'il n'est pas fait pour être utilisé, et qu'on exclu toute responsabilité. Et que si une personne (gouvernement ou quoi) souhaite supprimer ça, on le fera. Bon bien sur, faut tout bien faire rédiger ca par ChatGPT mais je penses que ça passes, faut voir

2023-08-11 14:32 UTC, matthieuEv commented
> Dac pour cheerio, dans tous les cas un jour j'écrirais des unit tests pour passer mon code, et si ça passe pas avec cheerio c'est que ça sera pas bon x)

Ouai tu me diras 👌

2023-08-11 14:36 UTC, Sylicium commented
> Dans ce cas la il suffit juste de mettre un avertissement au tout début du readme pour dire que ce repo est fait à des fin d'apprentissage et qu'il n'est pas fait pour être utilisé, et qu'on exclu toute responsabilité. Et que si une personne (gouvernement ou quoi) souhaite supprimer ça, on le fera. Bon bien sur, faut tout bien faire rédiger ca par ChatGPT mais je penses que ça passes, faut voir

Honnetement je pense pas que ça passera, j'avais déjà mis un warning dans le README pour dire si on veut couper l'api jla coupe direct, mais mon pote m'as dis qu'ils s'en foutait et que ce serait direct l'amende (de plusieur dizaine voire centaine de millier d'euro) donc bon x)
Mais ouai on fera ça, surtout pour le module NPM

2023-08-11 14:36 UTC, matthieuEv commented
pour `getPageDatas()`, est ce que tu peux me dire toutes les valeurs que tu voudrais dedans.

D'ailleurs, je penses que ça serait plus pratique pour toi de me mettre Contributor, et qu'on fasse des branches, avant de merge ça dans la main, comme ça tu peux toujours modif des truc sans que ça casse le main.

2023-08-11 14:42 UTC, Sylicium commented
Je connait pas super bien github mais jvais regarder pour te mettre contributor, et je comptait merge ton code dans une nouvlle branche cheerio.

et pour getPageDatas() j'aimerais que y'ai 2 options: category et pageID (à voir si y'a un page ID dans toutes les catégories ou si c'est que pour les films)
et ensuite ça handle sur le code approprié (qu'on séparera ptet en sous fichiers) pour fetch la page.
getPageDatas("films", "9734") appellera le fichier `./pageParsers/films.js` et le code dedans sera enfait l'ancien getMovieDetails()
et pour les autres catégories ça sera pareil sauf que le code sera fine tuné spécialement pour get les infos d'une catégorie en particulier (comme ça si les pages sont différents c'est plus simple pour spécifier)

2023-08-11 14:45 UTC, Sylicium approved these changes
Ready for pushing to cheerio branch

2023-08-11 14:47 UTC, merged

2023-08-11 14:49 UTC, Sylicium commented
Fait des push que sur la branche `cheerio` maintenant stp

2023-08-11 14:49 UTC, matthieuEv commented
> Je connait pas super bien github mais jvais regarder pour te mettre contributor, et je comptait merge ton code dans une nouvlle branche cheerio.
> 
> et pour getPageDatas() j'aimerais que y'ai 2 options: category et pageID (à voir si y'a un page ID dans toutes les catégories ou si c'est que pour les films) et ensuite ça handle sur le code approprié (qu'on séparera ptet en sous fichiers) pour fetch la page. getPageDatas("films", "9734") appellera le fichier `./pageParsers/films.js` et le code dedans sera enfait l'ancien getMovieDetails() et pour les autres catégories ça sera pareil sauf que le code sera fine tuné spécialement pour get les infos d'une catégorie en particulier (comme ça si les pages sont différents c'est plus simple pour spécifier)

Ok bah écoute, je vais refaire au propre la fonction `getPageDatas()` et du coup je te laisserai faire la modification que tu veux faire

2023-08-11 14:51 UTC, Sylicium commented
Nan touche à rien sur getPageDatas(), je m'en occuperais

2023-08-11 14:58 UTC, matthieuEv commented
ok mais essaye de faire avec le module cheerio, le code est beaucoup plus lisible, et ça fait plus claire car ça utilise une syntaxe équivalent à du Jquery

2023-08-11 15:14 UTC, Sylicium commented
J'essaierais, mais là je code plu le truc en ce moment j'ai d'autres trucs mais bon tkt avec ton code de TheMovieDatabase ça suffit pour que le code soit utilisable sans que y'ai besoin de mon code pour l'instant (d'ailleurs tu peux mettre une étoile au repo stp ? xd)

2023-08-11 17:21 UTC, matthieuEv commented
Seulement si t'active les contributeurs pour que je soit visible sur la page d'accueil 👌

2023-08-12 13:21 UTC, matthieuEv commented
https://github.com/matthieuEv/Zt-url-api

et je penses que ça serai plus pratique si on utilisait discord pour discuter plutôt que ici 😅
@themattnifique